[tools]
aqua = "latest"
# Python
python = "3.14.3"
"pipx:ansible" = "latest"
"pipx:python-openstackclient" = "latest"
# Go
go = "1.26.0"
"go:golang.org/x/tools/cmd/..." = "latest"
# Rust
rust = "stable"
# Node.js
nodejs = "24.14.0"
"npm:@antfu/ni" = "latest"
"npm:swagger2openapi" = "latest"
"npm:diff-so-fancy" = "latest"
"npm:redoc-cli" = "latest"
"npm:@redocly/cli" = "latest"
# Bun
bun = "1.3.10"
