[tools]
aqua = "latest"
# Python
python = "3.14.2"
"pipx:ansible" = "latest"
"pipx:python-openstackclient" = "latest"
# Go
go = "1.25.5"
"go:golang.org/x/tools/cmd/..." = "latest"
# Rust
rust = "stable"
# Node.js
nodejs = "24.12.0"
"npm:diff-so-fancy" = "latest"
"npm:redoc-cli" = "latest"
# Bun
bun = "1.3.5"
